### ISSUE TITLE
remove all SpaDES code from caching 

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#1]
`SpaDES` depends on `reproducible`, so we cannot have anything in this package depending on `SpaDES`. Currently, some `Cache` examples rely on `SpaDES`, and the documentation refers to `simList` objects. The code also heavily relies on elements of `SpaDES`, including `simList`s.

- [ ] documentation extensively refers to `SpaDES` (https://github.com/PredictiveEcology/reproducible/blob/master/R/cache.R#L27-L167)
- [ ] example relies on `SpaDES` (https://github.com/PredictiveEcology/reproducible/blob/master/R/cache.R#L197-L253)
- [ ] function code depends on `SpaDES` and/or `simList`s (*e.g.*, https://github.com/PredictiveEcology/reproducible/blob/master/R/cache.R#L274-L288; https://github.com/PredictiveEcology/reproducible/blob/master/R/cache.R#L314-L338; and others)

**Comment by eliotmcintire** [comment]
I have looked at all this, and I think the solution is to make SpaDES a "suggests" package. I believe that does not create circular dependencies (technically). The examples are labelled more clearly ... that they are about `simList` objects, from SpaDES package.

Having said that, it is not clear where the documentation would go otherwise. The SpaDES package is just adding a method for `robustDigest`; it is not adding a method to `Cache`. 

To be a little more precise, there is nothing in the code that relies on `simList` objects; rather, there are elements in the code that can accommodate `simList` objects, should they occur (which is what Suggests) is for.

**Comment by eliotmcintire** [comment]
After discussions with @achubaty , we decided to remove all references to simList and SpaDES. This required several new generic functions. There are now several of these in reproducible 499c0527e5d12282f6be27d96fa11bbf0193f56d, and new methods in SpaDES 61d3613d190803e32852d340328c4c0222638e53
