### ISSUE TITLE
verify prepInputs and friends cleanup after using raster functions

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#110]
because `raster` is sloppy about not cleaning up after itself, we should be more careful to keep track of temp files used by that package and cleanup afterwards.

**Comment by tati-micheletti** [comment]
reprex:

**Comment by tati-micheletti** [comment]
Not sure its not cleaning after itself, or not saving the raster in the proper folder...

**Comment by achubaty** [comment]
I updated your reprex, but note that I think `destinationPath` is being used incorrectly here, since it's not unzipping anything. Using `filename2` is more appropriate:

```r
out2 <- reproducible::postProcess(ras, rasterToMatch = RTM, filename2 = file.path(tempdir(), "out2.tif"))
file.exists(normPath(out2@file@name)) ## TRUE
list.files(tempWD) ## empty
list.files(tempdir()) ## out2.tif is here
```

Note that this does **not** reproduce the issue I was describing. I think you need out of memory rasters, and additional GIS operations to get leftover files in the temp raster dir.

**Comment by tati-micheletti** [comment]
True... I made this reprex on a problem I (thought I) was having: I would have expected that any saved files created would have been saved to the `destinationPath` provided (as happens when you are actually downloading and/or unzipping anything), but it was saved to the `wd`. So basically: 
- downloading/unzipping: if `destinationPath` is passed, It will be saved there, else will be saved in the `wd`.
- GIS operation without downloading/unzipping: `destinationPath` is not used, even if passed. If filename2 is passed, is where it will be saved. If not passed, it will be saved with a random `Smallxxx` in the wd. Also if I pass `filename2 = NULL` it doesn't save anything anywhere.

**Comment by achubaty** [comment]
good news! recent `raster` versions have become really good (maybe too aggressive?) about cleaning up after itself. closing.
