### ISSUE TITLE
clean up for stricter r-devel checking

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#12]
previous failures on r-devel appear to be resolved in 3c679dc16430bbc3fda2c39302de3c5358b3fcaf

currently, tests failing due to warnings during checks:

1.  r-devel is stricter about R versions. Use 3.3.0 as dependency instead of 3.3.3 if possible.

    ```r
    * checking DESCRIPTION meta-information ... WARNING
    Dependence on R version ‘3.3.3’ not with patchlevel 0
    ```
2. recheck documentation.

    ```r
    * checking for code/documentation mismatches ... WARNING
    Codoc mismatches from documentation object 'package_dependenciesMem':
    available.packagesMem
      Code: function(contriburl = contrib.url(repos, type), method, fields
             = NULL, type = getOption("pkgType"), filters = NULL,
             repos = getOption("repos"), ignore_repo_cache = FALSE,
             max_repo_cache_age, ...)
      Docs: function(contriburl = contrib.url(repos, type), method, fields
             = NULL, type = getOption("pkgType"), filters = NULL,
             repos = getOption("repos"))
      Argument names in code not in docs:
        ignore_repo_cache max_repo_cache_age ...
    ```

**Comment by eliotmcintire** [comment]
Well that is unfair!  utils::available.packages has 2 new arguments in `R-devel`, so the `@inheritParams` tag doesn't work correctly. Since I will build the manuals on my machine and push to travis, it will be mismatched from either the `R-devel` (if I make manuals on my current `R`) or mismatched with `R-release` (if I make manuals on `R-devel`). This is a problem because the `utils` package is part of base `R`, and I can't separate the version of utils from the R version.

**Comment by achubaty** [comment]
resolved in branch
