### ISSUE TITLE
Please add rgdal to package dependenices

### ISSUE THREAD

**Issue by chrismallon** [PredictiveEcology/reproducible#210]
Hello,

Thank you very much for your work on ```reproducible```! It is increasingly becoming part of my daily workflows.

After installing the library through ```renv::intall```, I called ```prepInputs```, and received the following error:

```Error in .requireRgdal() : package 'rgdal' is not available```

This resolved after ```renv::install('rgdal')```. Could you please add ```rgdal``` to the dependencies, so that it is  installed whenever you install ```reproducible```?

Thank you for your time!

**Comment by achubaty** [comment]
`rgdal` is listed in Suggests, to keep the total number of firm dependencies as small as possible.

When installing, us `install.packages("reproducible", dependencies = TRUE)` or similar to install _all_ dependencies.

**Comment by eliotmcintire** [comment]
Thanks for the feedback! It is nice to hear. 

As @achubaty indicated, CRAN has a policy that forces packages to keep their `imports` down. We need to fix the error that you are seeing so that it doesn't just error. Most of the functions have versions that work without gdal. But, the correct way to install it is with the recommendation above: `install.packages("reproducible", dependencies = TRUE)`

**Comment by achubaty** [comment]
Closing, as we are removing the dependency on `rgdal` as part of the changes to other spatial packages (`sf`, `raster`, etc.) to deprecating that package.
