### ISSUE TITLE
duplicate cache directories being made

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#50]
Even though cache dir is specified as `cache/SMALL` (sometimes `cache/SMALL_All` gets used), I get extra cache directories being made:

```
cache/
  |_SMALL/
  |_SMALL_All/
  |_SMALL_2All/
  |_SMALL_3All/
  ...
```

**Comment by eliotmcintire** [comment]
There are 2 caches in LandWeb. You can change this, but currently, there are two. One has size (e.g., SMALL) and the other is size + ownership (e.g., SMALL_ALL). They are both specified in the global_file.R.

As for the other ones, SMALL_2All and SMALL_3All, those may be old? It used to be used. If you have them recently, then that should be changed.

Since we are now NOT distinguishing based on data ownership at the Cache level, we may want to remove the 2 Caches and just use 1 of them for all things.

**Comment by achubaty** [comment]
These are new directories being made, and I can't seem to find where/why they are being created.
