### ISSUE TITLE
cache operations on large caches take up too much memory

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#67]
```r
> clearCache(x = paths$cachePath, userTags = "binaryRaster1")
Cache size:
 Total (including Rasters): 979.1 Gb
 Selected objects (not including Rasters): 69.3 Gb
Error: cannot allocate vector of size 5.0 Gb
```

Perhaps do things in "chunks", otherwise need to avoid storing such large objects in memory.

**Comment by achubaty** [comment]
see also b8c8ba6ef8fefa1b4683974b5492a1f1ccd9cce3

**Comment by achubaty** [comment]
this could probably be improved further, but i'm closing for now

**Comment by eliotmcintire** [comment]
I am going to revert the `pbapply` stuff because it should be unnecessary. The removal of these large "non-file-backed" rasters is just like any other object in the Cache. The special ones are the "file-backed rasters". Those ones have very small `.rda` files in the gallery because they only have metadata, so are identifiable.
