### ISSUE TITLE
'Require' returns uninformative error if package is already loaded [minor]

### ISSUE THREAD

**Issue by tati-micheletti** [PredictiveEcology/reproducible#92]
reprex:
```
reproducible::Require(raster) # works fine
reproducible::Require(raster) # Error in Require(raster) : packages should be a character vector or a name
```

**Comment by eliotmcintire** [comment]
That is actually very imformative, and solves your problem:
```
reproducible::Require(raster) # works fine
reproducible::Require(raster) # Error in Require(raster) : packages should be a character vector or a name
reproducible::Require("raster")
```

It "tries" the first time to use the "object" called `raster`... since it does not exist, it tries to interpret it as a character string. The second time, the package is loaded, so the "object" called `raster` does exist.  So, it tries to load that object (it is the function `raster::raster`). The third, and correct time, is the best way to always load a library/package in R. It does "work" in base R to use require(raster) ... but that not great for `Require` for some other reasons.
